version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "mission-admin-stack"
s3_bucket = "phase0-hackathon"
s3_prefix = "mission-admin"
region = "eu-central-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=dev"
image_repositories = []